# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sdm < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-sdm"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-sdm/releases/download/v0.2.0/sdm_0.2.0_darwin_amd64.tar.gz"
      sha256 "90dc0d66a3763ad80ccad2bff8f7298a32aba42551c8d56a7b694e517f4e43f6"

      define_method(:install) do
        bin.install "sdm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-sdm/releases/download/v0.2.0/sdm_0.2.0_darwin_arm64.tar.gz"
      sha256 "f5263023d5d68f08cc28d99c4029a1018d4568525113a4e7553a8b6f141a1012"

      define_method(:install) do
        bin.install "sdm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-sdm/releases/download/v0.2.0/sdm_0.2.0_linux_amd64.tar.gz"
      sha256 "2e9c5026a4192f664561ad77b0a3c90d4fe6f892c8409187cd27296c9536a8bc"
      define_method(:install) do
        bin.install "sdm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-sdm/releases/download/v0.2.0/sdm_0.2.0_linux_arm64.tar.gz"
      sha256 "e403c2bc0bcee45b25dbee85190bc8fe70b16b6dbb6bace8a58a4a794efc4208"
      define_method(:install) do
        bin.install "sdm"
      end
    end
  end

  test do
    assert_match "sdm", shell_output("#{bin}/sdm version")
  end
end
