# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Svctool < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-sdm"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-sdm/releases/download/v0.1.0/homebrew-sdm_0.1.0_darwin_amd64.tar.gz"
      sha256 "07b0df8cb686900847c87cc4ddc8725415054b2209ae26de03e5a1068af8238a"

      define_method(:install) do
        bin.install "svctool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-sdm/releases/download/v0.1.0/homebrew-sdm_0.1.0_darwin_arm64.tar.gz"
      sha256 "d6c1db8c3d620eece969abfe907624b0ccee051b68a085ec9190c0be471ca7a3"

      define_method(:install) do
        bin.install "svctool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-sdm/releases/download/v0.1.0/homebrew-sdm_0.1.0_linux_amd64.tar.gz"
      sha256 "1cc49e4d0fe41848d3fe1b4589e1d96c6e34b4cfd8c6c681ecb11fefd0756046"
      define_method(:install) do
        bin.install "svctool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-sdm/releases/download/v0.1.0/homebrew-sdm_0.1.0_linux_arm64.tar.gz"
      sha256 "25177a0011e1271ffe09f5b2b25ab5c7085e3daf94549473c3afade3394c1717"
      define_method(:install) do
        bin.install "svctool"
      end
    end
  end

  test do
    assert_match "svctool", shell_output("#{bin}/svctool version")
  end
end
